### ISSUE TITLE
IndexError in critique_and_refine Method

### ISSUE THREAD

**Issue by cn-knight** [microsoft/PromptWizard#12]
IndexError in critique_and_refine Method
Error: IndexError: list index out of range occurs in the critique_and_refine method while accessing refined_prompts[0] after applying regex matching.
Cause: The regex pattern DatasetSpecificProcessing.TEXT_DELIMITER_PATTERN fails to find any matches in the response content generated by chat_completion. This results in an empty list, causing the out-of-range access.
Impact: The project fails to complete the prompt refinement step, halting the execution of get_best_prompt.
Steps to Reproduce:
Call the method gp.get_best_prompt(use_examples=True, run_without_train_examples=False, generate_synthetic_examples=False).
Observe the failure during the execution of the critique_and_refine method in core_logic.py.
Suggested Fix:
Add a validation check to handle cases where regex matches are empty:
python
Copy code
matches = re.findall(DatasetSpecificProcessing.TEXT_DELIMITER_PATTERN, refined_prompts)
if not matches:
    raise ValueError(
        "Regex pattern did not match any content in refined_prompts. Check if the prompt generation or regex pattern is correct."
    )
refined_prompts = matches[0]
Debug the raw response content (refined_prompts) to confirm its format and ensure compatibility with the regex pattern.
Additional Notes:
The issue seems related to incorrect or incomplete responses generated by chat_completion.
Ensure that the regex pattern (DatasetSpecificProcessing.TEXT_DELIMITER_PATTERN) matches the format of the refined_prompts content.
Verify the behavior of the chat_completion function and confirm that it generates a valid output for refinement.

**Comment by raghav-2002-os** [comment]
Hi, thanks for your comments. This error occurs when the language model used doesn't give the output in the right format. Re-running the code will usually resolve this issue.

**Comment by ergosumdre** [comment]
> Hi, thanks for your comments. This error occurs when the language model doesn't give the output in the expected format. Re-running the code will usually resolve this issue.

Hello, I received the same twice error, even after re-running the code.
