### ISSUE TITLE
CritiqueNRefineParams: Missing 1 required positional argument: 'num_train_examples'

### ISSUE THREAD

**Issue by kartiksubodh** [microsoft/PromptWizard#13]
Num_train_examples is missing in  prompt_opt_config.yaml, leading to an exception while generating the GluePromptOpt object

Exception logs:
CritiqueNRefineParams.__init__() missing 1 required positional argument: 'num_train_examples'

Possible fix:
Add num_train_examples in the prompt_opt_config.yaml 

Also, num_train_examples refers to the number of synthetic examples to be generated. Ideally, this should be optional, and it can also be named better.

**Comment by raghav-2002-os** [comment]
Hi, thanks for your comments. We have updated the relevant files so that the errors don't occur. Please try using the updated code
