### ISSUE TITLE
can it support other platforms  api-key

### ISSUE THREAD

**Issue by redpintings** [microsoft/PromptWizard#14]
Does it only support OpenAI keys, and can it support other platforms such as Google. GLM4 Deepseek

**Comment by raghav-2002-os** [comment]
Hi, thanks for your comments. We do support OpenAI keys. Please follow the steps shown in the section : https://github.com/microsoft/PromptWizard?tab=readme-ov-file#high-level-overview-of-using-promptwizard

**Comment by rabner** [comment]
What about local API endpoints compatible with OpenAI? Ollama?

**Comment by redpintings** [comment]
ok i will try

**Comment by redpintings** [comment]
Do you have any plans to add models compatible with the OpenAI interface in the future? You only need to support passing base_url and api_key

**Comment by redpintings** [comment]
This is a great project. Do you have any plans in the future to support models that are compatible with the SDK for OpenAI? If not, I may not be following this project anymore. If only supporting OpenAI is supported, the path for this project will be too narrow

**Comment by raghav-2002-os** [comment]
Hi,
To use any of the above-mentioned LLM calling methodologies like local API endpoints or SDK for OpenAI the changes need to made only to the following function : https://github.com/microsoft/PromptWizard/blob/0d22cd25133b4a42db1a8a37b3c2ffa7598d5207/promptwizard/glue/common/llm/llm_mgr.py#L17
This function takes as input a message, queries the LLM and returns the LLM response. Hope this helps!
