### ISSUE TITLE
是否支持优化中文提示词？

### ISSUE THREAD

**Issue by ikumiyo** [microsoft/PromptWizard#15]
优化中文提示词的数据怎么样？

**Comment by raghav-2002-os** [comment]
Hi, 
For Chinese prompts you would require a Chinese Language Model

**Comment by langcaiye** [comment]
> Hi, For Chinese prompts you would require a Chinese Language Model

But isn't GPT a multilingual model?

**Comment by datalee** [comment]
yes,such as qwen72,
how can i use it with vllm openai serving?
