### ISSUE TITLE
Inconsistent pattern and prompt

### ISSUE THREAD

**Issue by klimagor** [microsoft/PromptWizard#16]
The definition of `<\END>` tag in the `TEXT_DELIMITER_PATTERN_MUTATION` is inconsistent with `<END>` tag in the `meta_sample_template`:

```python
TEXT_DELIMITER_PATTERN_MUTATION = r"(?s)(?<=<START>)(.*?)(?=</END>)"
```

```yaml
meta_sample_template: |
  You are given a task description and a prompt instruction and different styles known as meta prompts:
  [Task Description]: {task_description}
  [Meta Prompt]: {meta_prompts}
  Now you need to generate {num_variations} variations of following Instruction adaptively mixing meta prompt while keeping similar semantic meaning.
  Make sure to wrap each generated prompt with <START> and <END>
  [Prompt Instruction]: {prompt_instruction}
  [Generated Prompts]:
```

Maybe  `TEXT_DELIMITER_PATTERN_MUTATION` should be changed to `<END>` like in other places

**Comment by raghav-2002-os** [comment]
Hi, thanks for your comments. 
Please let us know in case you face an error while running the code. To the best of our knowledge, the current setting seems to be working fine

**Comment by klimagor** [comment]
The problem occurs in `promptwizard/glue/promptopt/techniques/critique_n_refine/core_logic.py` in line 114:
```python
matches = re.findall(DatasetSpecificProcessing.TEXT_DELIMITER_PATTERN_MUTATION, generated_mutated_prompt)
```

`matches` become empty list, because `generated_mutated_prompt` icnludes `<END>` tag instead of `<\END>` tag in the `TEXT_DELIMITER_PATTERN_MUTATION`

It was experienced by running `demos/scenarios/dataset_scenarios_demo.ipynb`: 
`Scenario 1 : We have no training data , but we also don't want in-context examples in final prompt` with OpenAI `gpt-4o-mini` model
