### ISSUE TITLE
gen_different_styles includes a base prompt in the form of task_desc + instruction

### ISSUE THREAD

**Issue by shentongmartin** [microsoft/PromptWizard#19]
during the resample by mutation step, candidate prompts is initialized with the following line:
```
candidate_prompts = [task_description + "\n" + base_instruction]
```

which seems to be a bit odd, since task_description shouldn't go into the optimization process, and should only impact the expert_profile and intents.

**Comment by raghav-2002-os** [comment]
Hi,
Thanks for your comments. To the best of our knowledge, the current code is correct
