### ISSUE TITLE
solve_template does not take task_desc into account

### ISSUE THREAD

**Issue by shentongmartin** [microsoft/PromptWizard#20]
the supplied solve_template is:
```
  You are given a prompt instruction and the following {questions_batch_size} questions of the same task.
  [Instruction]: {instruction}

  [Question]: {questions}

  {answer_format}

  [Answers]:
```

which does not have a placeholder for task description, and it will negatively impact LLM's performance during scoring. Is it intended behavior?

**Comment by raghav-2002-os** [comment]
Hi,
Thanks for your comments. To the best of our knowledge, the current code is correct
