### ISSUE TITLE
Feat: Add support for Azure OpenAI api key

### ISSUE THREAD

**Issue by wtberry** [microsoft/PromptWizard#22]
# Problem Statement
For azure openai api, authentication by api key is not supported.

# Proposed Solution
I propose to support this use case by adding small modification to the function below.
* `promptwizard/glue/common/llm/llm_mgr.py` > `call_api()`

# Development Consideration
* Please let me know if there's anything I need to take into account, besides modifying the file above.

# Related Issuses
* https://github.com/microsoft/PromptWizard/issues/18

**Comment by raghav-2002-os** [comment]
Hi,
Thanks for your comments. By changing the following function any LLM calling resource can be used https://github.com/microsoft/PromptWizard/blob/60504476f8231a7cb0fc3182101a86014e3b73ee/promptwizard/glue/common/llm/llm_mgr.py#L17
