### ISSUE TITLE
Optimizing Dynamic Prompts

### ISSUE THREAD

**Issue by Anchaliya75** [microsoft/PromptWizard#9]
# Description
Can we optimize prompts which are Dynamic i.e Prompts contains variables 
An example Prompt can be 

"""
You are an AI chatbot you must never answer/ respond to off-topic categories given here
 <off-topic-list>{{off-topics-list}} </off-topic-list>
Description of each off-topic is also there in the list
<off-topic-description> {{off-topic-description}}.</off-topic-description>
Generate response based on given
<query>{{query}}</query>
"""

Can we optimize these kind of prompts. Are there any checks which will ensure that llm doesn't change any of these variables?

**Comment by deathsaber** [comment]
Hi. I had this same use case and did it by replacing the variables with temporary place-holders and, in the fine-tuned prompt, put back the variables  where they were appropriate.

**Comment by raghav-2002-os** [comment]
Hi, thanks for your comments. For dynamic prompts you can separate out the instructions and the placeholder section, i.e. have all the instructions together at the beginning and then dynamically append the placeholder content after all the instructions. and optimise only the instructions. Also, you can have sections with headings for the placeholder content and reference those section headings in your instructions.
 
For your use case you can do the following :
 
You are an AI chatbot you must never answer/ respond to off-topic categories given in OFF_TOPICS_DESCRIPTION section
Description of each off-topic is also there in OFF_TOPICS_LIST section
Generate response based on given query in QUERY section
 
OFF_TOPICS_DESCRIPTION
{off-topic-description content comes here...}
OFF_TOPICS_LIST
{off-topics-list content comes here..}
QUERY
{query content comes here...}
